mode: webcam
velocity: 0.8
steer_sensitivity: 0.04
debug_window: True
image_width : 640
image_height : 480
birdeye_warp_param:
  top: 265
  bottom: 320
  top_width: 120
  bottom_width: 180
  birdeye_width: 180
filter_thr_dict:
  saturation_thr: [3,23]
  x_grad_thr: [65,200]
  red_thr: [127,178]
  green_thr: [112,184]
  blue_thr: [118,192]
