mode : webcam
velocity : 0.13
steer_sensitivity : 0.003
debug_window : True
image_width : 320
image_height : 240
birdeye_warp_param : 
  top : 85
  bottom : 213
  top_width : 73
  bottom_width : 179
  birdeye_width : 180
filter_thr_dict : 
  saturation_thr : [3,23]
  x_grad_thr : [65,200]
  red_thr : [127,178]
  green_thr : [112,184]
  blue_thr : [118,192]
