


controller_frequency: 20.0
controller_patience: 5.0

planner_frequency: 5.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

shutdown_costmaps: false

recovery_behavior_enabled: false
conservative_reset_dist: 3.0

clearing_rotation_allowed: false
