header:
  stamp: now
  frame_id: base_footprint
polygon:
  points:
  - x: 0.23
    y: 0.146
    z: 0.0
  - x: -0.29
    y: 0.146
    z: 0.0
  - x: -0.29
    y: -0.146
    z: 0.0
  - x: 0.23
    y: -0.146
    z: 0.0
